name: BackEnd Unit Test

on:
  pull_request:

jobs:
  unit_test:
    name: BackEnd unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dep
        working-directory: dl-flow-backend
        run: pnpm Install
      - name: Run Test
        working-directory: dl-flow-backend
        run: pnpm test