name: BackEnd Unit Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    name: BackEnd unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dep
        run: |
          cd dl-flow-backend
          pnpm install
      - name: Run Test
        run: |
          cd dl-flow-backend
          pwd
          pnpm test