name: BackEnd Unit Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    name: BackEnd unit Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dl-flow-backend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
          cache-dependency-path: 'dl-flow-backend/pnpm-lock.yaml'
      - name: Install dep
        run: pnpm install
      - name: Run Test
        run: pnpm test